apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno
  template:
    metadata:
      labels:
        app: eno
    spec:
      containers:
        - name: eno
          image: laurentc35/eno-ws:latest
          env:
            - name: FR_INSEE_ENOWS_API_SCHEME
              value: "https"
            - name: FR_INSEE_ENOWS_API_HOST
              value: "queen.demo.dev.sspcloud.fr"
